# Generated by Django 5.2 on 2025-04-28 06:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=users.models.GenerateProfileImgPath()),
        ),
    ]
